# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       xorg-x11-util-macros
Summary:    X.Org X11 Autotools macros
Version:    1.16.0
Release:    0
Group:      Development/System
License:    The Open Group License
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/util/util-macros-%{version}.tar.bz2
Source100:  xorg-x11-util-macros.yaml
Provides:   xorg-macros


%description
This is a set of autoconf macros used by the configure.ac scripts individual
other Xorg modular packages, and is needed to generate new versions
of their configure scripts with autoconf.




%prep
%setup -q -n util-macros-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%doc COPYING ChangeLog
%{_datadir}/aclocal/xorg-macros.m4
%{_datadir}/pkgconfig/xorg-macros.pc
%{_datadir}/util-macros/INSTALL
# << files


